[package]
name = "sdl2_playbook"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sdl2 = { version = "0.35.2", features = [] }
rand = "0.8"

